deployments:
  manager:
    replicas: 1
    containers:
      c0:
        image: 'clv2.cargo.io/release/katib-db-manager:v0.9.2'
        imagePullPolicy: Always
        command:
        - ./katib-db-manager
        ports:
          http:
            containerPort: 6789
            protocol: TCP
        env:
        - name: KATIB_MYSQL_DB_HOST
          value: "am-mysql.default"
        - name: DB_NAME
          value: "mysql"
        - name: KATIB_MYSQL_DB_DATABASE
          value: "am"
        - name: DB_PASSWORD
          value: "my-secret-pw"
        resources:
          limits:
            cpu: 600m
            memory: 600Mi
          requests:
            cpu: 100m
            memory: 100Mi
services:
  manager:
    type: ClusterIP
    ports:
      http:
        port: 6789
        protocol: TCP
        targetPort: 6789
