apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - name: webhook
      port: {{ .Values.serverPort.webhook.port }}
      targetPort: {{ .Values.serverPort.webhook.targetPort }}
      protocol: TCP
    - name: metrics
      port: {{ .Values.serverPort.metrics.port }}
      protocol: TCP
      targetPort: {{ .Values.serverPort.metrics.targetPort }}
  {{- if .Values.service.extraPorts }}
  {{- include "common.tplvalues.render" (dict "value" .Values.service.extraPorts "context" $) | nindent 4 }}
  {{- end }}

