apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      containers:
      - image: {{ include "common.images.image" (dict "context" $ "repository" .Values.platformConfig.imageRepositoryRelease "imageRoot" .Values.image) | quote }}
        imagePullPolicy: {{ default "Always" .Values.platformConfig.imagePullPolicy | quote }}
        name: {{ include "common.names.fullname" . }}
        command: 
          {{- range $.Values.command }}
          - {{ . | quote }}
          {{- end }}
        env:
          - name: DB_NAME
            value: "mysql"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: katib-mysql-secrets
                key: MYSQL_ROOT_PASSWORD
        ports:
        {{- if .Values.serverPort }}
        - name: {{ .Values.serverPort.name }}
          containerPort: {{ .Values.serverPort.port }}
        {{- end }}
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe: {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}