platformConfig:
  imageRegistry: xxx.cargo.io
  imageRepositoryRelease: release
  imagePullPolicy: Always

image:
  name: katib-controller

command:
  - ./katib-controller
  - -webhook-inject-securitycontext
  - -enable-grpc-probe-in-suggestion=false
  - --webhook-port=8443
  - -cert-localfs

service:
  name: controller
  type: ClusterIP

serverPort:
  webhook:
    port: 443
    targetPort: 8443
  metrics:
    port: 8080
    targetPort: 8080

configMapRef:
  name: katib-config

suggestion:
  random:
    name: suggestion-hyperopt
    tag: v0.9.2
  grid:
    name: suggestion-chocolate
    tag: v0.9.2
  hyperband:
    name: suggestion-hyperband
    tag: v0.9.2
  bayesianoptimization:
    name: suggestion-skopt
    tag: v0.9.2
  tpe:
    name: suggestion-hyperopt
    tag: v0.9.2

metrics_collector_sidecar:
  StdOut:
    name: file-metrics-collector
    tag: v0.9.2
  File:
    name: file-metrics-collector
    tag: v0.9.2
