# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oneshot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='oneshot.proto',
  package='api.v1.alpha3',
  syntax='proto3',
  serialized_pb=_b('\n\roneshot.proto\x12\rapi.v1.alpha3\x1a\x1cgoogle/api/annotations.proto\"\x1d\n\x1bGetOneshotSuggestionRequest\"/\n\x19GetOneshotSuggestionReply\x12\x12\n\nonnx_model\x18\x01 \x01(\x0c\x32}\n\x11OneshotSuggestion\x12h\n\x0eGetSuggestions\x12*.api.v1.alpha3.GetOneshotSuggestionRequest\x1a(.api.v1.alpha3.GetOneshotSuggestionReply0\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_GETONESHOTSUGGESTIONREQUEST = _descriptor.Descriptor(
  name='GetOneshotSuggestionRequest',
  full_name='api.v1.alpha3.GetOneshotSuggestionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=91,
)


_GETONESHOTSUGGESTIONREPLY = _descriptor.Descriptor(
  name='GetOneshotSuggestionReply',
  full_name='api.v1.alpha3.GetOneshotSuggestionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='onnx_model', full_name='api.v1.alpha3.GetOneshotSuggestionReply.onnx_model', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['GetOneshotSuggestionRequest'] = _GETONESHOTSUGGESTIONREQUEST
DESCRIPTOR.message_types_by_name['GetOneshotSuggestionReply'] = _GETONESHOTSUGGESTIONREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetOneshotSuggestionRequest = _reflection.GeneratedProtocolMessageType('GetOneshotSuggestionRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETONESHOTSUGGESTIONREQUEST,
  __module__ = 'oneshot_pb2'
  # @@protoc_insertion_point(class_scope:api.v1.alpha3.GetOneshotSuggestionRequest)
  ))
_sym_db.RegisterMessage(GetOneshotSuggestionRequest)

GetOneshotSuggestionReply = _reflection.GeneratedProtocolMessageType('GetOneshotSuggestionReply', (_message.Message,), dict(
  DESCRIPTOR = _GETONESHOTSUGGESTIONREPLY,
  __module__ = 'oneshot_pb2'
  # @@protoc_insertion_point(class_scope:api.v1.alpha3.GetOneshotSuggestionReply)
  ))
_sym_db.RegisterMessage(GetOneshotSuggestionReply)



_ONESHOTSUGGESTION = _descriptor.ServiceDescriptor(
  name='OneshotSuggestion',
  full_name='api.v1.alpha3.OneshotSuggestion',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=142,
  serialized_end=267,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSuggestions',
    full_name='api.v1.alpha3.OneshotSuggestion.GetSuggestions',
    index=0,
    containing_service=None,
    input_type=_GETONESHOTSUGGESTIONREQUEST,
    output_type=_GETONESHOTSUGGESTIONREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ONESHOTSUGGESTION)

DESCRIPTOR.services_by_name['OneshotSuggestion'] = _ONESHOTSUGGESTION

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class OneshotSuggestionStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetSuggestions = channel.unary_stream(
          '/api.v1.alpha3.OneshotSuggestion/GetSuggestions',
          request_serializer=GetOneshotSuggestionRequest.SerializeToString,
          response_deserializer=GetOneshotSuggestionReply.FromString,
          )


  class OneshotSuggestionServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def GetSuggestions(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_OneshotSuggestionServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetSuggestions': grpc.unary_stream_rpc_method_handler(
            servicer.GetSuggestions,
            request_deserializer=GetOneshotSuggestionRequest.FromString,
            response_serializer=GetOneshotSuggestionReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'api.v1.alpha3.OneshotSuggestion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaOneshotSuggestionServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def GetSuggestions(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaOneshotSuggestionStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def GetSuggestions(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()


  def beta_create_OneshotSuggestion_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('api.v1.alpha3.OneshotSuggestion', 'GetSuggestions'): GetOneshotSuggestionRequest.FromString,
    }
    response_serializers = {
      ('api.v1.alpha3.OneshotSuggestion', 'GetSuggestions'): GetOneshotSuggestionReply.SerializeToString,
    }
    method_implementations = {
      ('api.v1.alpha3.OneshotSuggestion', 'GetSuggestions'): face_utilities.unary_stream_inline(servicer.GetSuggestions),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_OneshotSuggestion_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('api.v1.alpha3.OneshotSuggestion', 'GetSuggestions'): GetOneshotSuggestionRequest.SerializeToString,
    }
    response_deserializers = {
      ('api.v1.alpha3.OneshotSuggestion', 'GetSuggestions'): GetOneshotSuggestionReply.FromString,
    }
    cardinalities = {
      'GetSuggestions': cardinality.Cardinality.UNARY_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'api.v1.alpha3.OneshotSuggestion', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
